/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/packet.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/packet.pb-c.h"
void   audio__init
                     (Audio         *message)
{
  static const Audio init_value = AUDIO__INIT;
  *message = init_value;
}
size_t audio__get_packed_size
                     (const Audio *message)
{
  assert(message->base.descriptor == &audio__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t audio__pack
                     (const Audio *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &audio__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t audio__pack_to_buffer
                     (const Audio *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &audio__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Audio *
       audio__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Audio *)
     protobuf_c_message_unpack (&audio__descriptor,
                                allocator, len, data);
}
void   audio__free_unpacked
                     (Audio *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &audio__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   text__init
                     (Text         *message)
{
  static const Text init_value = TEXT__INIT;
  *message = init_value;
}
size_t text__get_packed_size
                     (const Text *message)
{
  assert(message->base.descriptor == &text__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t text__pack
                     (const Text *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &text__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t text__pack_to_buffer
                     (const Text *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &text__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Text *
       text__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Text *)
     protobuf_c_message_unpack (&text__descriptor,
                                allocator, len, data);
}
void   text__free_unpacked
                     (Text *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &text__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   command__init
                     (Command         *message)
{
  static const Command init_value = COMMAND__INIT;
  *message = init_value;
}
size_t command__get_packed_size
                     (const Command *message)
{
  assert(message->base.descriptor == &command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t command__pack
                     (const Command *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t command__pack_to_buffer
                     (const Command *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Command *
       command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Command *)
     protobuf_c_message_unpack (&command__descriptor,
                                allocator, len, data);
}
void   command__free_unpacked
                     (Command *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   device_info__init
                     (DeviceInfo         *message)
{
  static const DeviceInfo init_value = DEVICE_INFO__INIT;
  *message = init_value;
}
size_t device_info__get_packed_size
                     (const DeviceInfo *message)
{
  assert(message->base.descriptor == &device_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t device_info__pack
                     (const DeviceInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &device_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t device_info__pack_to_buffer
                     (const DeviceInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &device_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeviceInfo *
       device_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeviceInfo *)
     protobuf_c_message_unpack (&device_info__descriptor,
                                allocator, len, data);
}
void   device_info__free_unpacked
                     (DeviceInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &device_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   packet__head__init
                     (Packet__Head         *message)
{
  static const Packet__Head init_value = PACKET__HEAD__INIT;
  *message = init_value;
}
void   packet__init
                     (Packet         *message)
{
  static const Packet init_value = PACKET__INIT;
  *message = init_value;
}
size_t packet__get_packed_size
                     (const Packet *message)
{
  assert(message->base.descriptor == &packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t packet__pack
                     (const Packet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t packet__pack_to_buffer
                     (const Packet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Packet *
       packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Packet *)
     protobuf_c_message_unpack (&packet__descriptor,
                                allocator, len, data);
}
void   packet__free_unpacked
                     (Packet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor audio__field_descriptors[3] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Audio, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sample_rate",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Audio, sample_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channels",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Audio, channels),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned audio__field_indices_by_name[] = {
  2,   /* field[2] = channels */
  0,   /* field[0] = data */
  1,   /* field[1] = sample_rate */
};
static const ProtobufCIntRange audio__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor audio__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Audio",
  "Audio",
  "Audio",
  "",
  sizeof(Audio),
  3,
  audio__field_descriptors,
  audio__field_indices_by_name,
  1,  audio__number_ranges,
  (ProtobufCMessageInit) audio__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor text__field_descriptors[1] =
{
  {
    "text",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Text, text),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned text__field_indices_by_name[] = {
  0,   /* field[0] = text */
};
static const ProtobufCIntRange text__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor text__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Text",
  "Text",
  "Text",
  "",
  sizeof(Text),
  1,
  text__field_descriptors,
  text__field_indices_by_name,
  1,  text__number_ranges,
  (ProtobufCMessageInit) text__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor command__field_descriptors[1] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Command, command),
    &commands__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned command__field_indices_by_name[] = {
  0,   /* field[0] = command */
};
static const ProtobufCIntRange command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Command",
  "Command",
  "Command",
  "",
  sizeof(Command),
  1,
  command__field_descriptors,
  command__field_indices_by_name,
  1,  command__number_ranges,
  (ProtobufCMessageInit) command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor device_info__field_descriptors[5] =
{
  {
    "display_height",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DeviceInfo, has_display_height),
    offsetof(DeviceInfo, display_height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "display_width",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DeviceInfo, has_display_width),
    offsetof(DeviceInfo, display_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "play_sample_rate",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DeviceInfo, has_play_sample_rate),
    offsetof(DeviceInfo, play_sample_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "play_bps",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DeviceInfo, has_play_bps),
    offsetof(DeviceInfo, play_bps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "play_channels",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DeviceInfo, has_play_channels),
    offsetof(DeviceInfo, play_channels),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned device_info__field_indices_by_name[] = {
  0,   /* field[0] = display_height */
  1,   /* field[1] = display_width */
  3,   /* field[3] = play_bps */
  4,   /* field[4] = play_channels */
  2,   /* field[2] = play_sample_rate */
};
static const ProtobufCIntRange device_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor device_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeviceInfo",
  "DeviceInfo",
  "DeviceInfo",
  "",
  sizeof(DeviceInfo),
  5,
  device_info__field_descriptors,
  device_info__field_indices_by_name,
  1,  device_info__number_ranges,
  (ProtobufCMessageInit) device_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor packet__head__field_descriptors[3] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Packet__Head, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Packet__Head, type),
    &message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_info",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Packet__Head, device_info),
    &device_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned packet__head__field_indices_by_name[] = {
  2,   /* field[2] = device_info */
  1,   /* field[1] = type */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange packet__head__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor packet__head__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Packet.Head",
  "Head",
  "Packet__Head",
  "",
  sizeof(Packet__Head),
  3,
  packet__head__field_descriptors,
  packet__head__field_indices_by_name,
  1,  packet__head__number_ranges,
  (ProtobufCMessageInit) packet__head__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor packet__field_descriptors[4] =
{
  {
    "head",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Packet, head),
    &packet__head__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audio",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Packet, body_case),
    offsetof(Packet, audio),
    &audio__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "text",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Packet, body_case),
    offsetof(Packet, text),
    &text__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Packet, body_case),
    offsetof(Packet, command),
    &command__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned packet__field_indices_by_name[] = {
  1,   /* field[1] = audio */
  3,   /* field[3] = command */
  0,   /* field[0] = head */
  2,   /* field[2] = text */
};
static const ProtobufCIntRange packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Packet",
  "Packet",
  "Packet",
  "",
  sizeof(Packet),
  4,
  packet__field_descriptors,
  packet__field_indices_by_name,
  1,  packet__number_ranges,
  (ProtobufCMessageInit) packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue message_type__enum_values_by_number[3] =
{
  { "MESSAGE_TYPE_AUDIO", "MESSAGE_TYPE__MESSAGE_TYPE_AUDIO", 0 },
  { "MESSAGE_TYPE_TEXT", "MESSAGE_TYPE__MESSAGE_TYPE_TEXT", 1 },
  { "MESSAGE_TYPE_COMMAND", "MESSAGE_TYPE__MESSAGE_TYPE_COMMAND", 2 },
};
static const ProtobufCIntRange message_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex message_type__enum_values_by_name[3] =
{
  { "MESSAGE_TYPE_AUDIO", 0 },
  { "MESSAGE_TYPE_COMMAND", 2 },
  { "MESSAGE_TYPE_TEXT", 1 },
};
const ProtobufCEnumDescriptor message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MessageType",
  "MessageType",
  "MessageType",
  "",
  3,
  message_type__enum_values_by_number,
  3,
  message_type__enum_values_by_name,
  1,
  message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue commands__enum_values_by_number[1] =
{
  { "COMMANDS_CLEAR_HISTORY", "COMMANDS__COMMANDS_CLEAR_HISTORY", 1 },
};
static const ProtobufCIntRange commands__value_ranges[] = {
{1, 0},{0, 1}
};
static const ProtobufCEnumValueIndex commands__enum_values_by_name[1] =
{
  { "COMMANDS_CLEAR_HISTORY", 0 },
};
const ProtobufCEnumDescriptor commands__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Commands",
  "Commands",
  "Commands",
  "",
  1,
  commands__enum_values_by_number,
  1,
  commands__enum_values_by_name,
  1,
  commands__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
